cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIA5D7543TRV4VSKHFL
      secret-key: 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